export const GET_COURSES_RESPONSE = 'GET_COURSES_RESPONSE';
export const GET_COURSE_RESPONSE = 'GET_COURSE_RESPONSE';
export const ADD_NEW_COURSE_RESPONSE = 'ADD_NEW_COURSE_RESPONSE';
export const UPDATE_EXISTING_COURSE_RESPONSE = 'UPDATE_EXISTING_COURSE_RESPONSE';
export const DELETE_COURSE_RESPONSE = 'DELETE_COURSE_RESPONSE';

export const GET_AUTHORS_RESPONSE = 'GET_AUTHORS_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';

//Products
export const GET_PRODUCTS_RESPONSE='GET_PRODUCTS_RESPONSE';
export const ADD_NEW_PRODUCT_RESPONSE='ADD_NEW_PRODUCT_RESPONSE';
export const UPDATE_PRODUCT_RESPONSE='UPDATE_PRODUCT_RESPONSE';
export const DELETE_PRODUCT_RESPONSE='DELETE_PRODUCT_RESPONSE';
