//Products
export const GET_PRODUCTS_RESPONSE='GET_PRODUCTS_RESPONSE';
export const ADD_NEW_PRODUCT_RESPONSE='ADD_NEW_PRODUCT_RESPONSE';
export const UPDATE_PRODUCT_RESPONSE='UPDATE_PRODUCT_RESPONSE';
export const DELETE_PRODUCT_RESPONSE='DELETE_PRODUCT_RESPONSE';
export const GET_PRODUCT_RESPONSE='GET_PRODUCT_RESPONSE';
export const DISPOSE_SELECTED_PRODUCT='DISPOSE_SELECTED_PRODUCT';

//Customers
export const GET_CUSTOMERS_RESPONSE='GET_CUSTOMERS_RESPONSE'
export const ADD_NEW_CUSTOMER_RESPONSE='ADD_NEW_CUSTOMER_RESPONSE';
export const UPDATE_CUSTOMER_RESPONSE='UPDATE_CUSTOMER_RESPONSE';
export const DELETE_CUSTOMER_RESPONSE='DELETE_CUSTOMER_RESPONSE';
export const GET_CUSTOMER_RESPONSE='GET_CUSTOMER_RESPONSE';
